### ISSUE TITLE
Feed Output Not Transformed

### ISSUE THREAD

**Issue by earthtone** [onecrayon/gridsome-plugin-feed#2]
I've been trying to implement this plugin for a simple blog using the `@gridsome/source-filesystem` plugin and the `remark` transformer. The plugin generates feeds perfectly, but the content of each feed item is raw Markdown text and not the transformed HTML text I was expecting. 

Poking around, it looks like the `collection` returned from `api.store.getContentType` holds each items "un-transformed" content data. Do you know if there is there another way to see the same data _after_ it has been transformed using the same `afterBuild` hook?

Below is how I have the plugin configured in my config file:

```js
[{
    use: 'gridsome-plugin-feed',
    options: {
      contentTypes: ['BlogPost'],
      feedOptions: {
        title: 'Six Impossible Things',
        description: 'Musings and ramblings'
      },
      rss: {
        enabled: true,
        output: '/feed.xml'
      },
      atom: {
        enabled: true,
        output: '/feed.atom'
      },
      json: {
        enabled: true,
        output: '/feed.json'
      },
      nodeToFeedItem: node => ({
        title: node.title,
        description: node.description,
        date: new Date(node.date),
        content: node.content,
        author: 'Tonio Hubilla',
        url: 'https://ton-hub.net/' + node.path
      })
    }
}]
```

I'm running version `1.0.2` of the plugin with version `0.6.9` of gridsome.

**Comment by onecrayon** [comment]
That's bizarre; I didn't realize it wasn't converting content because my primary feed content is already in HTML (thanks to cross-publishing it places where Markdown isn't an option). I've poked around in the internals of the `node` object, and unfortunately it doesn't appear to have converted content stashed anywhere (though oddly, it does have a field for the content prior to getting run through the Remark transformer, because it has all the metadata included in that field).

I will do some more testing and see if I can find a good alternative.

**Comment by earthtone** [comment]
@onecrayon Thanks for checking on this!

From the shallow understanding I have of the Server API, since I can see HTML content returned in the GraphQL explorer I _assumed_ transforms were run on content types when they are **put** into the Data Store early on in the build process. Maybe this is a naive assumption to make, and they are actually transformed on each **get**? Is that plausible?

I'll continue to poke around and see what some of the other `api` hooks provide.

**Comment by onecrayon** [comment]
> Maybe this is a naive assumption to make, and they are actually transformed on each get? Is that plausible?

That was the whole reason I was hooking onto `afterBuild`, actually; my understanding of how the app worked was at this point everything would be parsed, but evidently this method of getting data out of the GraphQL layer is not working like I thought.

**Comment by earthtone** [comment]
@onecrayon It looks like my suspicion was correct, and transforms are occurring in the in the GraphQL layer as mentioned in [this issue response](https://github.com/gridsome/gridsome/issues/514#issuecomment-510481670l). I've checked it out and this solution works great for my use case. 

Thanks for looking into this, and thanks for developing this plugin!

**Comment by RehanSaeed** [comment]
Is there a way to get the full HTML with all remark plugins I've configured in Gridsome?

https://github.com/gridsome/gridsome/issues/514#issuecomment-510481670l does not take any custom remark plugins into consideration and just does basic markdown to HTML.

**Comment by onecrayon** [comment]
@RehanSaeed Please open a new issue and I will take a look when I am able (time has been booked pretty solid, but I'm hoping to get my darn Gridsome plugins up to date soon).

**Comment by RehanSaeed** [comment]
Done

https://github.com/onecrayon/gridsome-plugin-feed/issues/6
